/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{html,md,mdx,js,jsx,ts,tsx}"],
	darkMode: "media",
	theme: {
		extend: {
			colors: {
				warm: {
					1: "var(--warm-1)",
					2: "var(--warm-2)",
					3: "var(--warm-3)",
					4: "var(--warm-4)",
					5: "var(--warm-5)",
					6: "var(--warm-6)",
					7: "var(--warm-7)",
					8: "var(--warm-8)",
					9: "var(--warm-9)",
					10: "var(--warm-10)",
					11: "var(--warm-11)",
					12: "var(--warm-12)",
				},
				"warm-inverse": {
					1: "var(--warm-inverse-1)",
					2: "var(--warm-inverse-2)",
					3: "var(--warm-inverse-3)",
					4: "var(--warm-inverse-4)",
					5: "var(--warm-inverse-5)",
					6: "var(--warm-inverse-6)",
					7: "var(--warm-inverse-7)",
					8: "var(--warm-inverse-8)",
					9: "var(--warm-inverse-9)",
					10: "var(--warm-inverse-10)",
					11: "var(--warm-inverse-11)",
					12: "var(--warm-inverse-12)",
				},
				primary: {
					DEFAULT: "var(--primary)",
					1: "var(--primary-1)",
					2: "var(--primary-2)",
					3: "var(--primary-3)",
					4: "var(--primary-4)",
					5: "var(--primary-5)",
					6: "var(--primary-6)",
					7: "var(--primary-7)",
					8: "var(--primary-8)",
					9: "var(--primary-9)",
					10: "var(--primary-10)",
					11: "var(--primary-11)",
					12: "var(--primary-12)",
				},
				neutral: {
					1: "var(--neutral-1)",
					2: "var(--neutral-2)",
					3: "var(--neutral-3)",
					4: "var(--neutral-4)",
					5: "var(--neutral-5)",
					6: "var(--neutral-6)",
					7: "var(--neutral-7)",
					8: "var(--neutral-8)",
					9: "var(--neutral-9)",
					10: "var(--neutral-10)",
					11: "var(--neutral-11)",
					12: "var(--neutral-12)",
				},
				"neutral-inverse": {
					1: "var(--neutral-inverse-1)",
					2: "var(--neutral-inverse-2)",
					3: "var(--neutral-inverse-3)",
					4: "var(--neutral-inverse-4)",
					5: "var(--neutral-inverse-5)",
					6: "var(--neutral-inverse-6)",
					7: "var(--neutral-inverse-7)",
					8: "var(--neutral-inverse-8)",
					9: "var(--neutral-inverse-9)",
					10: "var(--neutral-inverse-10)",
					11: "var(--neutral-inverse-11)",
					12: "var(--neutral-inverse-12)",
				},
				// Semantic tokens
				content: {
					neutral: {
						primary: "var(--content-warm)",
						secondary: "var(--content-warm-secondary)",
					},
				},
				border: {
					neutral: "var(--border-warm)",
				},
				text: {
					secondary: "var(--text-secondary)",
				},
			},
			fontFamily: {
				sans: ["Inter", "sans-serif"],
				mono: ["JetBrains Mono", "monospace"],
			},
		},
	},
	plugins: [],
};
